dist: trusty

language: go

go:
  - 1.13
  - master

notifications:
  email: false

addons:
  sonarcloud:
    organization: "negapedia"
    token:
      secure: "Dm2VMid3H++Eih9p/1lwTNkY8OokdGrM55VpOv0UZds51XTeDxoKeWs0C5y4eBnQ8/LzEWJ4mCYVNnethLObtsoJsHspbvaQ/cKg1601cKXEel0PE64d+ZVYNhdqtfZtRTRX+t9c4AzgT9bE1ZjlkDY2NuDS1Gcm4wzM0qei2K/kPNdR5fOkneaW7A4Cfd516kAzESpbkvsl3SerRWZgX7UtfdVlAG56+UQg4nE5EHawyuCz0vM4uZNXDuRAb5SXS3Ngclh32mkdNZUE6XnOnxDH/qQb+UrR3oO1mlK+pTBtW5cqFSq0tqh9jk7umSRufjTTNMpPgz0lh5W6z7ydb9dJnKeWqc+f9lQ0c/265cbzYdPPKG0uIQYuEgJsbiV8FC3gz9pwN8Nd0I/Rrq5pQfrGKvXY0BeEneFLB/JHs6B42m1im7qGAuOMzrVDPuIqjk62+i7OAU7VmTB12ooVHvAxLKJOAECAAn8KSBoVmFZu0WatujBcnXdm8N64Tfvy+e/ReI20cVhG2QivGkdXEA5Ukc7o+fu6KvDmJpVzxwbqKfoAelbWo/SNIgQxCoyGqlkrjNspVEq+igHLge4FeUYZ46NOW711Lg8+rB6Gjg+XK5a8UmIQQqN6adLHAAbXw1x30Fn2MFKJ3H+22XOqMmCHSvRUKCX8pFea2TtYq88="

script:
  - go test -race ./... -coverprofile=coverage.out
  - sonar-scanner -Dsonar.projectKey=negapedia_wikibots -Dsonar.projectName=wikibots -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.tests=. -Dsonar.test.inclusions=**/*_test.go -Dsonar.go.coverage.reportPaths=coverage.out